// This unit is autogenerated. Do not edit it manually.
// Source: JSON entered in editor
// Date: 29/9/2023 7:37:41 PM

unit JSONRPC.Web3.SolanaTypes.getVoteAccountResultsType;

interface

uses
  System.JSON.Serializers;

type
  [JsonSerialize(TJsonMemberSerialization.Fields)]
  TEpochCredit = record
  private
    [JsonName('Array')]
    FArray_: TArray<Integer>;
  public
    property Array_: TArray<Integer> read FArray_ write FArray_;
  end;

  [JsonSerialize(TJsonMemberSerialization.Fields)]
  TEpochCredit_1 = record
  private
    [JsonName('Array')]
    FArray_: TArray<Integer>;
  public
    property Array_: TArray<Integer> read FArray_ write FArray_;
  end;

  [JsonSerialize(TJsonMemberSerialization.Fields)]
  TCurrent = record
  private
    FactivatedStake: Integer;
    Fcommission: Integer;
    FepochCredits: TArray<TEpochCredit>;
    FepochVoteAccount: Boolean;
    FlastVote: Integer;
    FnodePubkey: string;
    FrootSlot: Integer;
    FvotePubkey: string;
  public
    property activatedStake: Integer read FactivatedStake write FactivatedStake;
    property commission: Integer read Fcommission write Fcommission;
    property epochCredits: TArray<TEpochCredit> read FepochCredits write FepochCredits;
    property epochVoteAccount: Boolean read FepochVoteAccount write FepochVoteAccount;
    property lastVote: Integer read FlastVote write FlastVote;
    property nodePubkey: string read FnodePubkey write FnodePubkey;
    property rootSlot: Integer read FrootSlot write FrootSlot;
    property votePubkey: string read FvotePubkey write FvotePubkey;
  end;

  [JsonSerialize(TJsonMemberSerialization.Fields)]
  TDelinquent = record
  private
    FactivatedStake: Integer;
    Fcommission: Integer;
    FepochCredits: TArray<TEpochCredit_1>;
    FepochVoteAccount: Boolean;
    FlastVote: Integer;
    FnodePubkey: string;
    FrootSlot: Integer;
    FvotePubkey: string;
  public
    property activatedStake: Integer read FactivatedStake write FactivatedStake;
    property commission: Integer read Fcommission write Fcommission;
    property epochCredits: TArray<TEpochCredit_1> read FepochCredits write FepochCredits;
    property epochVoteAccount: Boolean read FepochVoteAccount write FepochVoteAccount;
    property lastVote: Integer read FlastVote write FlastVote;
    property nodePubkey: string read FnodePubkey write FnodePubkey;
    property rootSlot: Integer read FrootSlot write FrootSlot;
    property votePubkey: string read FvotePubkey write FvotePubkey;
  end;

  [JsonSerialize(TJsonMemberSerialization.Fields)]
  TgetVoteAccountsResult = record
  private
    Fcurrent: TArray<TCurrent>;
    Fdelinquent: TArray<TDelinquent>;
  public
    property current: TArray<TCurrent> read Fcurrent write Fcurrent;
    property delinquent: TArray<TDelinquent> read Fdelinquent write Fdelinquent;
  end;

implementation

end.
